# Generated by Django 5.0.2 on 2024-11-13 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_tecnologias_api', '0005_rename_clave_alumno_alumnos_matricula_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestros',
            name='edad',
        ),
    ]
