# Generated by Django 5.0.2 on 2024-11-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_tecnologias_api', '0006_remove_maestros_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestros',
            name='fecha_nacimiento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
