# Generated by Django 5.0.2 on 2024-11-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_tecnologias_api', '0007_alter_maestros_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='fecha_nacimiento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
