# Generated by Django 5.0.2 on 2024-12-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_tecnologias_api', '0008_alter_alumnos_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nrc', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_materia', models.CharField(blank=True, max_length=255, null=True)),
                ('seccion', models.CharField(blank=True, max_length=255, null=True)),
                ('dias_json', models.TextField(blank=True, null=True)),
                ('hora_inicio', models.CharField(blank=True, max_length=255, null=True)),
                ('hora_fin', models.CharField(blank=True, max_length=255, null=True)),
                ('salon', models.CharField(blank=True, max_length=255, null=True)),
                ('programa', models.CharField(blank=True, max_length=255, null=True)),
                ('profesor', models.CharField(blank=True, max_length=255, null=True)),
                ('creditos', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
